# Ansible
ansible_python_interpreter: "/usr/bin/python3"

# Shipmate
shipmate_cargo_dir: "{{ lookup('env','SHIPMATE_CARGO_DIR') | default(lookup('env','PWD'), true) }}"
shipmate_provider: "{{ lookup('env','SHIPMATE_PROVIDER') | default('ansible-galaxy', true) }}"
shipmate_providers: "{{ lookup('env','SHIPMATE_PROVIDERS').split(',') | default(['ansible-galaxy'], true) }}"
shipmate_name: "{{ lookup('env','SHIPMATE_NAME') | default('', true) }}"
shipmate_author_name: "{{ lookup('env','SHIPMATE_AUTHOR_NAME') | default(shipmate_name, true) }}"
shipmate_description: "{{ lookup('env','SHIPMATE_DESCRIPTION') | default('', true) }}"
shipmate_tag: "{{ lookup('env','SHIPMATE_TAG') | default('', true) }}"
shipmate_author: "{{ lookup('env','SHIPMATE_AUTHOR') | default('', true) }}"
shipmate_author_url: "{{ lookup('env','SHIPMATE_AUTHOR_URL') | default('', true) }}"
shipmate_tags: "{{ lookup('env','SHIPMATE_TAGS') | default([ansible], true) }}"
shipmate_repository: "{{ lookup('env','SHIPMATE_REPOSITORY') | default('', true) }}"
shipmate_docs: "{{ lookup('env','SHIPMATE_DOCS') | default('', true) }}"
shipmate_website: "{{ lookup('env','SHIPMATE_WEBSITE') | default('', true) }}"
shipmate_issues: "{{ lookup('env','SHIPMATE_ISSUES') | default('', true) }}"
shipmate_version_file: "{{ lookup('env','SHIPMATE_VERSION_FILE') | default('VERSION.txt', true) }}"
shipmate_shipfile: "{{ lookup('env','SHIPMATE_SHIPFILE') | default('Shipfile', true) }}"
shipmate_cargo_version: "{{ lookup('env','SHIPMATE_CARGO_VERSION') | default('', true) }}"

# Provider: GitLab
gitlab_token: "{{ lookup('env','GITLAB_TOKEN') | default('', true) }}"
gl_token: "{{ lookup('env','GL_TOKEN') | default('', true) }}"

# Provider: ansible-galaxy
ansible_galaxy_token: "{{ lookup('env','ANSIBLE_GALAXY_TOKEN') | default('', true) }}"
ansible_galaxy_namespace: "{{ lookup('env','ANSIBLE_GALAXY_NAMESPACE') | default('derfabianpeter', true) }}"
ansible_galaxy_author_name: "{{ lookup('env','ANSIBLE_GALAXY_AUTHOR_NAME') | default(shipmate_author_name, true) }}"