# Ansible
ansible_python_interpreter: "/usr/bin/python3"

# Shipmate
shipmate_project_name: "{{ lookup('env', 'CI_PROJECT_NAME') | default(lookup('env', 'PWD')) }}"
shipmate_build_dir: "{{ lookup('env', 'CI_BUILDS_DIR')+'/'+lookup('env', 'CI_PROJECT_PATH') | default('/cargo') }}"
shipmate_cargo_dir: "{{ lookup('env','SHIPMATE_CARGO_DIR') | default(shipmate_build_dir, true) }}"
shipmate_provider: "{{ lookup('env','SHIPMATE_PROVIDER') | default('ansible-galaxy', true) }}"
shipmate_providers: "{{ lookup('env','SHIPMATE_PROVIDERS').split(',') | default('gitlab'.split(','), true) }}"
shipmate_name: "{{ lookup('env','SHIPMATE_NAME') | default('', true) }}"
shipmate_author_name: "{{ lookup('env','SHIPMATE_AUTHOR_NAME') | default(shipmate_name, true) }}"
shipmate_description: "{{ lookup('env','SHIPMATE_DESCRIPTION') | default('', true) }}"
shipmate_tag: "{{ lookup('env','SHIPMATE_TAG') | default('', true) }}"
shipmate_author: "{{ lookup('env','SHIPMATE_AUTHOR') | default('', true) }}"
shipmate_author_url: "{{ lookup('env','SHIPMATE_AUTHOR_URL') | default('', true) }}"
shipmate_tags: "{{ lookup('env','SHIPMATE_TAGS') | default([ansible], true) }}"
shipmate_repository: "{{ lookup('env','SHIPMATE_REPOSITORY') | default('', true) }}"
shipmate_docs: "{{ lookup('env','SHIPMATE_DOCS') | default('', true) }}"
shipmate_website: "{{ lookup('env','SHIPMATE_WEBSITE') | default('', true) }}"
shipmate_issues: "{{ lookup('env','SHIPMATE_ISSUES') | default('', true) }}"
shipmate_version_file: "{{ lookup('env','SHIPMATE_VERSION_FILE') | default('VERSION.txt', true) }}"
shipmate_shipfile: "{{ lookup('env','SHIPMATE_SHIPFILE') | default('shipmate.env', true) }}"
shipmate_cargo_version: "{{ lookup('env','SHIPMATE_CARGO_VERSION') | default('', true) }}"

shipmate_commit_id: "{{ lookup('env', 'CI_COMMIT_SHA') | default(lookup('pipe', 'git rev-parse HEAD'), true) }}"
shipmate_branch: "{{ lookup('env', 'CI_COMMIT_REF_NAME') | default('master', true) }}"
shipmate_default_branch: "{{ lookup('env', 'CI_DEFAULT_BRANCH') | default('master', true) }}"
shipmate_stage: "{{ lookup('env', 'SHIPMATE_STAGE') | default(lookup('env','CI_JOB_STAGE') | default('tag', true)) }}"
shipmate_merge_request: "{{ lookup('env', 'CI_MERGE_REQUEST_IID') }}"

# Provider: Docker
docker_image: "{{ lookup('env', 'CI_REGISTRY_IMAGE')+'/'+lookup('env', 'CI_COMMIT_REF_SLUG')+':'+lookup('env', 'CI_COMMIT_SHA') | default(shipmate_project_name+':'+shipmate_commit_id) }}"
docker_image_name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') | default(shipmate_project_name,true) }}"
docker_image_branch: "{{ lookup('env', 'CI_COMMIT_REF_SLUG') | default(shipmate_default_branch,true) }}"
docker_image_tag: "{{ lookup('env', 'CI_COMMIT_SHA') | default(shipmate_commit_id,true) }}"
docker_image_repository: "{{ lookup('env', 'CI_REGISTRY_IMAGE') | default('',true) }}"

# Provider: Git
git_default_remote:

# Provider: GitLab
gitlab_token: "{{ lookup('env','GITLAB_TOKEN') | default('', true) }}"
gl_token: "{{ lookup('env','GL_TOKEN') | default('', true) }}"

# Provider: ansible-galaxy
ansible_galaxy_token: "{{ lookup('env','ANSIBLE_GALAXY_TOKEN') | default('', true) }}"
ansible_galaxy_namespace: "{{ lookup('env','ANSIBLE_GALAXY_NAMESPACE') | default('derfabianpeter', true) }}"
ansible_galaxy_author_name: "{{ lookup('env','ANSIBLE_GALAXY_AUTHOR_NAME') | default(shipmate_author_name, true) }}"