include:
  - remote: 'https://gitlab.com/peter.saarland/scratch/-/raw/master/ci/templates/default.gitlab-ci.yml'

  #- remote: 'https://gitlab.com/peter.saarland/shipmate/-/raw/master/shipmate.gitlab-ci.yml'