- name: "Ahoi!"
  hosts: shipmate
  connection: local
  gather_facts: false
  vars:
    shipmate_providers: "{{ lookup('env','SHIPMATE_PROVIDERS').split(',') | default('ansible-galaxy', true) | list }}"
    shipmate_provider: "{{ lookup('env','SHIPMATE_PROVIDER') | default('ansible-galaxy', true) }}"
    shipmate_cargo_dir: "{{ lookup('env','PWD') }}"
  tasks:
    - name: "Check!"
      include: build-environment.yml
      tags:
        - hoist
        - sail
    - name: "Hoist!"
      include: hoist.yml
      tags:
        - hoist
        - sail
    - name: "Sail!"
      include: "provider-{{ item }}.yml"
      with_items: "{{ shipmate_providers }}"
      tags:
        - sail
    