- name: Authenticate
  block:
    - name: Login to Registry
      command: echo {{ docker_image_registry_password }} | docker login {{ docker_image_registry }} --username={{ docker_image_registry_user }} --password-stdin
          chdir="{{ shipmate_cargo_dir }}" 
  when: >
    shipmate_ci and
    docker_image_registry_path != ''

- name: Build
  block:
    - name: Reporting
      debug:
        msg: "Building {{ docker_image }}"
        verbosity: 1
    
    - name: "Build {{ shipmate_cargo_version }}"
      command: docker build -t {{ docker_image }} --build-arg SHIPMATE_CARGO_VERSION={{ shipmate_cargo_version }} --build-arg DOCKER_BASE_IMAGE={{ docker_base_image }} .
        chdir="{{ shipmate_cargo_dir }}"
      register: shipmate_build_docker
    
    - name: "Push {{ shipmate_cargo_version }}"
      command: docker push {{ docker_image }}
        chdir="{{ shipmate_cargo_dir }}" 
      when: >
        docker_image_registry_path != ''
  when: >
    shipmate_stage == 'build' and 
    shipmate_cargo_version != '' and shipmate_cargo_version is defined

- name: Ship
  block:
    - name: Tag
      command: docker tag {{ docker_image }} {{ lookup('vars','docker_image_registry_path', default='')+docker_image_repository+'/'+docker_image_branch+':'+item }}
        chdir="{{ shipmate_cargo_dir }}" 
      with_items:
        -  "latest"
        - "v{{ shipmate_cargo_version }}"

    - name: Ship
      command: docker push {{ lookup('vars','docker_image_registry_path', default='')+docker_image_repository+'/'+docker_image_branch+':'+item }}
        chdir="{{ shipmate_cargo_dir }}"   
      with_items:
        -  "latest"
        - "v{{ shipmate_cargo_version }}"
      when: >
        docker_image_registry_path != ''
  when: >
    shipmate_stage == "ship"