- name: Authenticate
  block:
    - name: Login to Registry
      docker_login:
        registry: "{{ docker_image_registry }}"
        username: "{{ docker_image_registry_user }}"
        password: "{{ docker_image_registry_password }}"
        reauthorize: yes
  when: >
    shipmate_ci and
    docker_image_registry_path != ''

- name: Build
  block:
    - name: Reporting
      debug:
        msg: "Building {{ docker_image }}"
        verbosity: 1
    
    - name: "Build {{ shipmate_cargo_version }}"
      command: docker build -t {{ docker_image }} --build-arg SHIPMATE_CARGO_VERSION={{ shipmate_cargo_version }} --build-arg DOCKER_BASE_IMAGE={{ docker_base_image }} .
        chdir="{{ shipmate_cargo_dir }}"
      register: shipmate_build_docker

    - name: Reporting
      debug:
        msg: "{{ shipmate_build_docker.stdout.split('\n') }}"
        verbosity: 1
      when: >
        shipmate_build_docker.stdout_lines|length > 0
    
    - name: "Push {{ shipmate_cargo_version }}"
      command: docker push {{ docker_image }}
        chdir="{{ shipmate_cargo_dir }}" 
      register: shipmate_push_docker
      when: >
        docker_image_registry_path != ''
    
    - name: Reporting
      debug:
        msg: "{{ shipmate_push_docker.stdout.split('\n') }}"
        verbosity: 1
      when: >
        shipmate_push_docker.stdout_lines|length > 0
  when: >
    shipmate_stage == 'build' and 
    shipmate_cargo_version != '' and shipmate_cargo_version is defined

- name: Ship
  block:
    - name: Pull
      command: docker pull {{ docker_image }}
        chdir="{{ shipmate_cargo_dir }}" 
      when: >
        docker_image_registry_path != ''

    - name: Tag
      command: docker tag {{ docker_image }} {{ lookup('vars','docker_image_registry_path', default='')+docker_image_repository+'/'+docker_image_branch+':'+item }}
        chdir="{{ shipmate_cargo_dir }}" 
      register: shipmate_tag_docker
      with_items:
        -  "latest"
        - "v{{ shipmate_cargo_version }}"

    - name: Reporting
      debug:
        msg: "{{ shipmate_tag_docker.stdout.split('\n') }}"
        verbosity: 1
      when: >
      shipmate_tag_docker.stdout_lines|length > 0

    - name: Ship
      command: docker push {{ lookup('vars','docker_image_registry_path', default='')+docker_image_repository+'/'+docker_image_branch+':'+item }}
        chdir="{{ shipmate_cargo_dir }}"   
      with_items:
        -  "latest"
        - "v{{ shipmate_cargo_version }}"
      register: shipmate_push_docker
      when: >
        docker_image_registry_path != ''

    - name: Reporting
      debug:
        msg: "{{ shipmate_push_docker.stdout.split('\n') }}"
        verbosity: 1
      when: >
        shipmate_push_docker.stdout_lines|length > 0

  when: >
    shipmate_stage == "ship"