- name: "Ahoi!"
  hosts: shipmate
  connection: local
  gather_facts: false
  tasks:
    - name: "Running Stage"
      include: "stage-{{ shipmate_stage }}.yml"

    - name: "Clean up Paperwork"
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ shipmate_cargo_dir }}/{{ shipmate_version_file }}"
        - "{{ shipmate_cargo_dir }}/.releaserc.yml"
    
    - name: "Reporting on Shipment"
      debug:
        msg: 
          - "Stage: {{ shipmate_stage }}"
          - "Commit ID: {{ shipmate_commit_id }}"
          - "Branch: {{ shipmate_branch }}"
          - "Merge Request ID: {{ lookup('env', 'CI_MERGE_REQUEST_ID') | default('UNKNOWN') }}"
          - "Merge Request IID: {{ lookup('env', 'CI_MERGE_REQUEST_IID') | default('UNKNOWN') }}"
          - "Version: {{ shipmate_cargo_version }}"
      when: "shipmate_cargo_version != '' or shipmate_cargo_version is defined"