- name: "Ahoi!"
  hosts: shipmate
  connection: local
  gather_facts: true
  tasks:
    - name: Loading Default .releaserc
      template:
        src: templates/.releaserc.yml.j2
        dest: "{{ shipmate_cargo_dir }}/.releaserc.yml"

    - debug: 
        msg: 
          - "Shipmate Version: {{ this_version }}"
          - "Shipmate CI: {{ shipmate_ci }}"
          - "Shipmate Stage: {{ shipmate_stage }}"
          - "Shipmate Providers: {{ shipmate_providers }}"
          - "Shipmate Project Name: {{ shipmate_project_name }}"
          - "Shipmate Branch: {{ shipmate_branch }}"
    
    - name: "Running Stage"
      include: "stage-{{ shipmate_stage }}.yml"

    - name: "Clean up Paperwork"
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ shipmate_cargo_dir }}/{{ shipmate_version_file }}"
        - "{{ shipmate_cargo_dir }}/.releaserc.yml"
        - "{{ shipmate_cargo_dir }}/CHANGELOG.md"
      when: >
        not shipmate_ci
    
    - name: "Reporting on Shipment"
      debug:
        msg: 
          - "Shipmate Version: {{ this_version }}"
          - "Shipmate CI: {{ shipmate_ci }}"
          - "Shipmate Stage: {{ shipmate_stage }}"
          - "Shipmate Branch: {{ shipmate_branch }}"
          - "Shipmate Commit ID: {{ shipmate_commit_id }}"
          - "Shimate Commit Message: {{ shipmate_commit_message }}"
          - "Shipmate Docker Image: {{ docker_image }}"
          - "Shipmate Providers: {{ shipmate_providers_string }}"
          - "Shipmate Merge Request ID: {{ lookup('env', 'CI_MERGE_REQUEST_ID') | default('UNKNOWN', true) }}"
          - "Shipmate Merge Request IID: {{ lookup('env', 'CI_MERGE_REQUEST_IID') | default('UNKNOWN', true) }}"
          - "Shipmate Cargo Version: {{ shipmate_cargo_version | default('UKNOWN') }}"
      when: "shipmate_cargo_version != '' and shipmate_cargo_version is defined"