- name: "Shipmate"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    shipmate_providers: "{{ lookup('env','SHIPMATE_PROVIDERS').split(',') | default('ansible-galaxy', true) | list }}"
    shipmate_provider: "{{ lookup('env','SHIPMATE_PROVIDER') | default('ansible-galaxy', true) }}"
  tasks:
    - name: "Load Providers"
      include: "{{ item }}.yml"
      with_items: "{{ shipmate_providers }}"