- name: Ensure CHANGELOG.md exists
  file:
    path: "{{ shipmate_cargo_dir }}/CHANGELOG.md"
    state: touch

- name: Publish Release
  command: npx semantic-release
    chdir="{{ shipmate_cargo_dir }}"
  register: semantic_release

- name: Look what I found ...
  debug:
    msg: "SemRel Result: {{ semantic_release }}"
    verbosity: 1